/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Gross Weight and Manuel Ngola
 */
public class MenuPrincipal1 extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal1
     */
    public MenuPrincipal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnFornecedor = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnPrecos = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_menu_rounded_32px.png"))); // NOI18N
        jLabel2.setText("Comprador-Fornecedores");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnFornecedor.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_user_group_man_man_24px.png"))); // NOI18N
        btnFornecedor.setText("Cadastrar Fornecedor");
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 40));

        btnProduto.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_to_collection_24px.png"))); // NOI18N
        btnProduto.setText("Cadastrar Produto");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, 40));

        btnPrecos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnPrecos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gross Weight\\AppData\\Local\\Temp\\icons8_pricing_32px.png")); // NOI18N
        btnPrecos.setText("Definir Preços");
        btnPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 230, -1));

        btnCompra.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_buying_32px.png"))); // NOI18N
        btnCompra.setText("Criar Pedidos de Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 230, -1));

        btnListar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_todo_list_32px_1.png"))); // NOI18N
        btnListar.setText("Visualisar Pedidos");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, -1));

        btnSair.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exit_sign_32px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuprimcipAL_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        // TODO add your handling code here:
        new CadastroFornecedor().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        // TODO add your handling code here:
        new CadastroProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecosActionPerformed
        // TODO add your handling code here:
        new DefinirPreco().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPrecosActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
        new CriarPedidoCompra().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        new VisualizarPedidos().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPrecos;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
